server:
  port: 80


spring:
  mustache:
    # ??? ??? ???? .mustache? ???? ??? ??? ????? ??
    suffix: .mustache
    # src/main/resources/templates/a.mustache
    # src/main/resources/templates/
    prefix: classpath:/templates/
    # ?? ?? ?? ? ?? ????? ?? ??? ????(?? ?? ??)
    cache: false
    # ??? ??? UTF-8 ????? ????.
    charset: UTF-8

logging:
  level:
    # spring web ?? ??? DEBUG ?? ???? ??
    # ??? ??? ?? ?? ??? ????? ?? ????.
    org.springframework.web: DEBUG


